version: "2"
#docker run --rm --entrypoint htpasswd registry:2 -Bbn <username> "<password>" > ~/htpasswd_backup/htpasswd
#
services:
        registry:
                build: ./registry
                restart: always
                expose:
                        - 5000
                environment:
                        REGISTRY_AUTH: 'htpasswd'
                        REGISTRY_AUTH_HTPASSWD_REALM: 'RegistryRealm'
                        REGISTRY_AUTH_HTPASSWD_PATH: '/htpasswd'
                        TCP_PORTS: '5000'
                        VIRTUAL_HOST: '*:5000, https://*:5000'
                        FORCE_SSL: 'false'
                        REGISTRY_STORAGE_DELETE_ENABLED: 'true'
                ports:
                        - "5000:5000"
                volumes:
                        - ./local_registry:/var/lib/registry
                        - ./htpasswd:/htpasswd
        registry-ui:
                image: konradkleine/docker-registry-frontend:v2
                restart: always
                environment:
                        VIRTUAL_HOST: '*, https://*'
                        ENV_DOCKER_REGISTRY_HOST: 'registry'
                        ENV_DOCKER_REGISTRY_PORT: 5000
                        ENV_MODE_BROWSE_ONLY: 'false'
                links:
                        - registry
                expose:
                        - 80
                ports: 
                        - "81:80"
